import { FileUtils } from './utils/files.js';

export class Exporters {
    /**
     * Generates and downloads a CSV parts list
     * @param {Array} partsList - Array of { part, color, hex, qty }
     * @param {string} filename 
     */
    static downloadCSV(partsList, filename) {
        let csvContent = "Part Name,Color Name,Hex Code,Quantity\n";
        
        partsList.forEach(item => {
            // Escape quotes in names
            const part = item.part.replace(/"/g, '""');
            const color = item.color.replace(/"/g, '""');
            
            csvContent += `"${part}","${color}","${item.hex}",${item.qty}\n`;
        });

        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        FileUtils.downloadBlob(blob, filename || FileUtils.generateFilename('parts', 'csv'));
    }

    /**
     * Downloads the current canvas as a PNG
     * @param {HTMLCanvasElement} canvas 
     * @param {string} filename 
     */
    static downloadPNG(canvas, filename) {
        if (!canvas) {
            console.error("Exporters: No canvas provided");
            return;
        }
        
        // Convert canvas to blob for better large-file handling
        canvas.toBlob((blob) => {
            FileUtils.downloadBlob(blob, filename || FileUtils.generateFilename('render', 'png'));
        });
    }

    /**
     * Generates a basic HTML build guide
     * @param {object} metadata - { title, client, partsList }
     */
    static downloadHTML(metadata, filename) {
        const rows = metadata.partsList.map(p => 
            `<tr><td>${p.part}</td><td><span style="color:${p.hex}">■</span> ${p.color}</td><td>${p.qty}</td></tr>`
        ).join('');

        const html = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>${metadata.title} - Build Guide</title>
                <style>
                    body { font-family: sans-serif; padding: 2rem; max-width: 800px; margin: 0 auto; }
                    h1 { border-bottom: 2px solid #333; padding-bottom: 0.5rem; }
                    table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
                    th { text-align: left; background: #eee; padding: 0.5rem; }
                    td { padding: 0.5rem; border-bottom: 1px solid #ddd; }
                </style>
            </head>
            <body>
                <h1>${metadata.title}</h1>
                <p><strong>Client:</strong> ${metadata.client || 'N/A'}</p>
                <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
                <h2>Parts List</h2>
                <table>
                    <thead><tr><th>Part</th><th>Color</th><th>Qty</th></tr></thead>
                    <tbody>${rows}</tbody>
                </table>
                <p><em>Generated by BlockForge Platform</em></p>
            </body>
            </html>
        `;

        const blob = new Blob([html], { type: 'text/html' });
        FileUtils.downloadBlob(blob, filename || FileUtils.generateFilename('guide', 'html'));
    }
}