export const LEGO_BRICK_TYPES = [
    // ============ BASIC BRICKS ============
    {
        id: 'brick_1x1',
        name: 'Brick 1x1',
        width: 1,
        depth: 1,
        height: 1,
        studs: 1,
        category: 'basic',
        subcategory: 'brick',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.4,
        volume: 0.8,
        yearIntroduced: 1949,
        isCurrent: true,
        colors: ['all'],
        image: '📦',
        description: 'Standard 1x1 brick, the smallest building unit'
    },
    {
        id: 'brick_1x2',
        name: 'Brick 1x2',
        width: 1,
        depth: 2,
        height: 1,
        studs: 2,
        category: 'basic',
        subcategory: 'brick',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.8,
        volume: 1.6,
        yearIntroduced: 1949,
        isCurrent: true,
        colors: ['all'],
        image: '📦📦',
        description: 'Standard 1x2 brick'
    },
    {
        id: 'brick_1x3',
        name: 'Brick 1x3',
        width: 1,
        depth: 3,
        height: 1,
        studs: 3,
        category: 'basic',
        subcategory: 'brick',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 1.2,
        volume: 2.4,
        yearIntroduced: 1958,
        isCurrent: true,
        colors: ['all'],
        image: '📦📦📦',
        description: 'Standard 1x3 brick'
    },
    {
        id: 'brick_1x4',
        name: 'Brick 1x4',
        width: 1,
        depth: 4,
        height: 1,
        studs: 4,
        category: 'basic',
        subcategory: 'brick',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 1.6,
        volume: 3.2,
        yearIntroduced: 1958,
        isCurrent: true,
        colors: ['all'],
        image: '📦📦📦📦',
        description: 'Standard 1x4 brick'
    },
    {
        id: 'brick_1x6',
        name: 'Brick 1x6',
        width: 1,
        depth: 6,
        height: 1,
        studs: 6,
        category: 'basic',
        subcategory: 'brick',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 2.4,
        volume: 4.8,
        yearIntroduced: 1958,
        isCurrent: true,
        colors: ['all'],
        image: '📦📦📦📦📦📦',
        description: 'Standard 1x6 brick'
    },
    {
        id: 'brick_1x8',
        name: 'Brick 1x8',
        width: 1,
        depth: 8,
        height: 1,
        studs: 8,
        category: 'basic',
        subcategory: 'brick',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 3.2,
        volume: 6.4,
        yearIntroduced: 1958,
        isCurrent: true,
        colors: ['all'],
        image: '📦📦📦📦📦📦📦📦',
        description: 'Standard 1x8 brick'
    },
    {
        id: 'brick_2x2',
        name: 'Brick 2x2',
        width: 2,
        depth: 2,
        height: 1,
        studs: 4,
        category: 'basic',
        subcategory: 'brick',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 1.6,
        volume: 3.2,
        yearIntroduced: 1953,
        isCurrent: true,
        colors: ['all'],
        image: '🟦',
        description: 'Standard 2x2 brick'
    },
    {
        id: 'brick_2x3',
        name: 'Brick 2x3',
        width: 2,
        depth: 3,
        height: 1,
        studs: 6,
        category: 'basic',
        subcategory: 'brick',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 2.4,
        volume: 4.8,
        yearIntroduced: 1958,
        isCurrent: true,
        colors: ['all'],
        image: '📦📦📦\n📦📦📦',
        description: 'Standard 2x3 brick'
    },
    {
        id: 'brick_2x4',
        name: 'Brick 2x4',
        width: 2,
        depth: 4,
        height: 1,
        studs: 8,
        category: 'basic',
        subcategory: 'brick',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 3.2,
        volume: 6.4,
        yearIntroduced: 1949,
        isCurrent: true,
        colors: ['all'],
        image: '📦📦📦📦\n📦📦📦📦',
        description: 'Classic 2x4 brick, the most iconic LEGO piece'
    },
    {
        id: 'brick_2x6',
        name: 'Brick 2x6',
        width: 2,
        depth: 6,
        height: 1,
        studs: 12,
        category: 'basic',
        subcategory: 'brick',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 4.8,
        volume: 9.6,
        yearIntroduced: 1958,
        isCurrent: true,
        colors: ['all'],
        image: '📦📦📦📦📦📦\n📦📦📦📦📦📦',
        description: 'Standard 2x6 brick'
    },
    {
        id: 'brick_2x8',
        name: 'Brick 2x8',
        width: 2,
        depth: 8,
        height: 1,
        studs: 16,
        category: 'basic',
        subcategory: 'brick',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 6.4,
        volume: 12.8,
        yearIntroduced: 1958,
        isCurrent: true,
        colors: ['all'],
        image: '📦📦📦📦📦📦📦📦\n📦📦📦📦📦📦📦📦',
        description: 'Standard 2x8 brick'
    },
    {
        id: 'brick_4x4',
        name: 'Brick 4x4',
        width: 4,
        depth: 4,
        height: 1,
        studs: 16,
        category: 'basic',
        subcategory: 'brick',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 6.4,
        volume: 12.8,
        yearIntroduced: 1965,
        isCurrent: true,
        colors: ['all'],
        image: '🟥',
        description: 'Large 4x4 brick'
    },

    // ============ PLATES ============
    {
        id: 'plate_1x1',
        name: 'Plate 1x1',
        width: 1,
        depth: 1,
        height: 0.333, // 1/3 of brick height
        studs: 1,
        category: 'basic',
        subcategory: 'plate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.13,
        volume: 0.27,
        yearIntroduced: 1963,
        isCurrent: true,
        colors: ['all'],
        image: '🔳',
        description: 'Standard 1x1 plate, 1/3 brick height'
    },
    {
        id: 'plate_1x2',
        name: 'Plate 1x2',
        width: 1,
        depth: 2,
        height: 0.333,
        studs: 2,
        category: 'basic',
        subcategory: 'plate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.26,
        volume: 0.54,
        yearIntroduced: 1963,
        isCurrent: true,
        colors: ['all'],
        image: '🔳🔳',
        description: 'Standard 1x2 plate'
    },
    {
        id: 'plate_1x3',
        name: 'Plate 1x3',
        width: 1,
        depth: 3,
        height: 0.333,
        studs: 3,
        category: 'basic',
        subcategory: 'plate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.39,
        volume: 0.81,
        yearIntroduced: 1963,
        isCurrent: true,
        colors: ['all'],
        image: '🔳🔳🔳',
        description: 'Standard 1x3 plate'
    },
    {
        id: 'plate_1x4',
        name: 'Plate 1x4',
        width: 1,
        depth: 4,
        height: 0.333,
        studs: 4,
        category: 'basic',
        subcategory: 'plate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.52,
        volume: 1.08,
        yearIntroduced: 1963,
        isCurrent: true,
        colors: ['all'],
        image: '🔳🔳🔳🔳',
        description: 'Standard 1x4 plate'
    },
    {
        id: 'plate_1x6',
        name: 'Plate 1x6',
        width: 1,
        depth: 6,
        height: 0.333,
        studs: 6,
        category: 'basic',
        subcategory: 'plate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.78,
        volume: 1.62,
        yearIntroduced: 1963,
        isCurrent: true,
        colors: ['all'],
        image: '🔳🔳🔳🔳🔳🔳',
        description: 'Standard 1x6 plate'
    },
    {
        id: 'plate_1x8',
        name: 'Plate 1x8',
        width: 1,
        depth: 8,
        height: 0.333,
        studs: 8,
        category: 'basic',
        subcategory: 'plate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 1.04,
        volume: 2.16,
        yearIntroduced: 1963,
        isCurrent: true,
        colors: ['all'],
        image: '🔳🔳🔳🔳🔳🔳🔳🔳',
        description: 'Standard 1x8 plate'
    },
    {
        id: 'plate_2x2',
        name: 'Plate 2x2',
        width: 2,
        depth: 2,
        height: 0.333,
        studs: 4,
        category: 'basic',
        subcategory: 'plate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.52,
        volume: 1.08,
        yearIntroduced: 1963,
        isCurrent: true,
        colors: ['all'],
        image: '⬜',
        description: 'Standard 2x2 plate'
    },
    {
        id: 'plate_2x3',
        name: 'Plate 2x3',
        width: 2,
        depth: 3,
        height: 0.333,
        studs: 6,
        category: 'basic',
        subcategory: 'plate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.78,
        volume: 1.62,
        yearIntroduced: 1963,
        isCurrent: true,
        colors: ['all'],
        image: '🔳🔳🔳\n🔳🔳🔳',
        description: 'Standard 2x3 plate'
    },
    {
        id: 'plate_2x4',
        name: 'Plate 2x4',
        width: 2,
        depth: 4,
        height: 0.333,
        studs: 8,
        category: 'basic',
        subcategory: 'plate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 1.04,
        volume: 2.16,
        yearIntroduced: 1963,
        isCurrent: true,
        colors: ['all'],
        image: '🔳🔳🔳🔳\n🔳🔳🔳🔳',
        description: 'Standard 2x4 plate'
    },
    {
        id: 'plate_2x6',
        name: 'Plate 2x6',
        width: 2,
        depth: 6,
        height: 0.333,
        studs: 12,
        category: 'basic',
        subcategory: 'plate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 1.56,
        volume: 3.24,
        yearIntroduced: 1963,
        isCurrent: true,
        colors: ['all'],
        image: '🔳🔳🔳🔳🔳🔳\n🔳🔳🔳🔳🔳🔳',
        description: 'Standard 2x6 plate'
    },
    {
        id: 'plate_2x8',
        name: 'Plate 2x8',
        width: 2,
        depth: 8,
        height: 0.333,
        studs: 16,
        category: 'basic',
        subcategory: 'plate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 2.08,
        volume: 4.32,
        yearIntroduced: 1963,
        isCurrent: true,
        colors: ['all'],
        image: '🔳🔳🔳🔳🔳🔳🔳🔳\n🔳🔳🔳🔳🔳🔳🔳🔳',
        description: 'Standard 2x8 plate'
    },
    {
        id: 'plate_4x4',
        name: 'Plate 4x4',
        width: 4,
        depth: 4,
        height: 0.333,
        studs: 16,
        category: 'basic',
        subcategory: 'plate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 2.08,
        volume: 4.32,
        yearIntroduced: 1963,
        isCurrent: true,
        colors: ['all'],
        image: '⬜',
        description: 'Large 4x4 plate'
    },

    // ============ TILES ============
    {
        id: 'tile_1x1',
        name: 'Tile 1x1',
        width: 1,
        depth: 1,
        height: 0.167, // 1/6 of brick height
        studs: 0,
        category: 'decorative',
        subcategory: 'tile',
        type: 'smooth',
        isPlate: false,
        isTile: true,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.1,
        volume: 0.2,
        yearIntroduced: 1975,
        isCurrent: true,
        colors: ['all'],
        image: '▫️',
        description: 'Smooth 1x1 tile, no studs'
    },
    {
        id: 'tile_1x2',
        name: 'Tile 1x2',
        width: 1,
        depth: 2,
        height: 0.167,
        studs: 0,
        category: 'decorative',
        subcategory: 'tile',
        type: 'smooth',
        isPlate: false,
        isTile: true,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.2,
        volume: 0.4,
        yearIntroduced: 1975,
        isCurrent: true,
        colors: ['all'],
        image: '▫️▫️',
        description: 'Smooth 1x2 tile'
    },
    {
        id: 'tile_1x4',
        name: 'Tile 1x4',
        width: 1,
        depth: 4,
        height: 0.167,
        studs: 0,
        category: 'decorative',
        subcategory: 'tile',
        type: 'smooth',
        isPlate: false,
        isTile: true,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.4,
        volume: 0.8,
        yearIntroduced: 1975,
        isCurrent: true,
        colors: ['all'],
        image: '▫️▫️▫️▫️',
        description: 'Smooth 1x4 tile'
    },
    {
        id: 'tile_2x2',
        name: 'Tile 2x2',
        width: 2,
        depth: 2,
        height: 0.167,
        studs: 0,
        category: 'decorative',
        subcategory: 'tile',
        type: 'smooth',
        isPlate: false,
        isTile: true,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 0.4,
        volume: 0.8,
        yearIntroduced: 1981,
        isCurrent: true,
        colors: ['all'],
        image: '▫️',
        description: 'Smooth 2x2 tile'
    },

    // ============ SLOPES ============
    {
        id: 'slope_30_1x1',
        name: 'Slope 30° 1x1',
        width: 1,
        depth: 1,
        height: 0.667, // 2/3 brick height
        studs: 0,
        category: 'special',
        subcategory: 'slope',
        type: '30_degree',
        isPlate: false,
        isTile: false,
        isSlope: true,
        isRound: false,
        isTechnic: false,
        slopeAngle: 30,
        weight: 0.3,
        volume: 0.6,
        yearIntroduced: 1980,
        isCurrent: true,
        colors: ['all'],
        image: '↘️',
        description: '30 degree slope 1x1'
    },
    {
        id: 'slope_45_1x1',
        name: 'Slope 45° 1x1',
        width: 1,
        depth: 1,
        height: 1,
        studs: 0,
        category: 'special',
        subcategory: 'slope',
        type: '45_degree',
        isPlate: false,
        isTile: false,
        isSlope: true,
        isRound: false,
        isTechnic: false,
        slopeAngle: 45,
        weight: 0.4,
        volume: 0.8,
        yearIntroduced: 1980,
        isCurrent: true,
        colors: ['all'],
        image: '↘️',
        description: '45 degree slope 1x1'
    },
    {
        id: 'slope_45_2x1',
        name: 'Slope 45° 2x1',
        width: 2,
        depth: 1,
        height: 1,
        studs: 1,
        category: 'special',
        subcategory: 'slope',
        type: '45_degree',
        isPlate: false,
        isTile: false,
        isSlope: true,
        isRound: false,
        isTechnic: false,
        slopeAngle: 45,
        weight: 0.8,
        volume: 1.6,
        yearIntroduced: 1980,
        isCurrent: true,
        colors: ['all'],
        image: '↘️↘️',
        description: '45 degree slope 2x1'
    },
    {
        id: 'slope_45_2x2',
        name: 'Slope 45° 2x2',
        width: 2,
        depth: 2,
        height: 1,
        studs: 1,
        category: 'special',
        subcategory: 'slope',
        type: '45_degree',
        isPlate: false,
        isTile: false,
        isSlope: true,
        isRound: false,
        isTechnic: false,
        slopeAngle: 45,
        weight: 1.6,
        volume: 3.2,
        yearIntroduced: 1980,
        isCurrent: true,
        colors: ['all'],
        image: '↘️',
        description: '45 degree slope 2x2'
    },

    // ============ ROUND BRICKS ============
    {
        id: 'round_1x1',
        name: 'Round Brick 1x1',
        width: 1,
        depth: 1,
        height: 1,
        studs: 1,
        category: 'special',
        subcategory: 'round',
        type: 'cylinder',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: true,
        isTechnic: false,
        shape: 'cylinder',
        weight: 0.4,
        volume: 0.8,
        yearIntroduced: 1975,
        isCurrent: true,
        colors: ['all'],
        image: '🔴',
        description: 'Round 1x1 brick'
    },
    {
        id: 'round_2x2',
        name: 'Round Brick 2x2',
        width: 2,
        depth: 2,
        height: 1,
        studs: 1,
        category: 'special',
        subcategory: 'round',
        type: 'cylinder',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: true,
        isTechnic: false,
        shape: 'cylinder',
        weight: 1.6,
        volume: 3.2,
        yearIntroduced: 1975,
        isCurrent: true,
        colors: ['all'],
        image: '🔵',
        description: 'Round 2x2 brick'
    },

    // ============ TECHNIC BRICKS ============
    {
        id: 'technic_1x2',
        name: 'Technic Brick 1x2',
        width: 1,
        depth: 2,
        height: 1,
        studs: 2,
        category: 'technic',
        subcategory: 'brick',
        type: 'with_holes',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: true,
        holes: 1,
        weight: 0.8,
        volume: 1.6,
        yearIntroduced: 1977,
        isCurrent: true,
        colors: ['black', 'grey', 'red', 'blue', 'yellow'],
        image: '🔩',
        description: 'Technic brick with pin hole'
    },
    {
        id: 'technic_1x4',
        name: 'Technic Brick 1x4',
        width: 1,
        depth: 4,
        height: 1,
        studs: 4,
        category: 'technic',
        subcategory: 'brick',
        type: 'with_holes',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: true,
        holes: 2,
        weight: 1.6,
        volume: 3.2,
        yearIntroduced: 1977,
        isCurrent: true,
        colors: ['black', 'grey', 'red', 'blue', 'yellow'],
        image: '🔩🔩',
        description: 'Technic brick with two pin holes'
    },
    {
        id: 'technic_beam_1x2',
        name: 'Technic Beam 1x2',
        width: 1,
        depth: 2,
        height: 0.5,
        studs: 0,
        category: 'technic',
        subcategory: 'beam',
        type: 'beam',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: true,
        holes: 2,
        weight: 0.4,
        volume: 0.8,
        yearIntroduced: 1977,
        isCurrent: true,
        colors: ['black', 'grey', 'red', 'blue', 'yellow'],
        image: '⛓️',
        description: 'Technic beam with holes'
    },
    {
        id: 'technic_beam_1x4',
        name: 'Technic Beam 1x4',
        width: 1,
        depth: 4,
        height: 0.5,
        studs: 0,
        category: 'technic',
        subcategory: 'beam',
        type: 'beam',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: true,
        holes: 4,
        weight: 0.8,
        volume: 1.6,
        yearIntroduced: 1977,
        isCurrent: true,
        colors: ['black', 'grey', 'red', 'blue', 'yellow'],
        image: '⛓️⛓️',
        description: 'Technic beam with four holes'
    },

    // ============ SPECIAL SHAPES ============
    {
        id: 'bracket_1x1',
        name: 'Bracket 1x1',
        width: 1,
        depth: 1,
        height: 1,
        studs: 2,
        category: 'special',
        subcategory: 'bracket',
        type: 'right_angle',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        orientation: 'L-shaped',
        weight: 0.4,
        volume: 0.8,
        yearIntroduced: 1978,
        isCurrent: true,
        colors: ['all'],
        image: '⎣',
        description: 'Right angle bracket'
    },
    {
        id: 'hinge_1x2',
        name: 'Hinge Brick 1x2',
        width: 1,
        depth: 2,
        height: 1,
        studs: 2,
        category: 'special',
        subcategory: 'hinge',
        type: 'plate_hinge',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        movable: true,
        weight: 0.8,
        volume: 1.6,
        yearIntroduced: 1980,
        isCurrent: true,
        colors: ['black', 'grey', 'white', 'red', 'blue'],
        image: '🔄',
        description: 'Hinge brick for movable parts'
    },
    {
        id: 'headlight_brick',
        name: 'Headlight Brick',
        width: 1,
        depth: 1,
        height: 1,
        studs: 1,
        category: 'special',
        subcategory: 'modified',
        type: 'headlight',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        specialFeature: 'side stud',
        weight: 0.4,
        volume: 0.8,
        yearIntroduced: 1990,
        isCurrent: true,
        colors: ['all'],
        image: '💡',
        description: 'Brick with stud on side'
    },

    // ============ WINDOWS & DOORS ============
    {
        id: 'window_1x2x2',
        name: 'Window 1x2x2',
        width: 1,
        depth: 2,
        height: 2,
        studs: 2,
        category: 'architectural',
        subcategory: 'window',
        type: 'clear',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        isTransparent: true,
        weight: 1.6,
        volume: 3.2,
        yearIntroduced: 1978,
        isCurrent: true,
        colors: ['transClear', 'transBlack', 'transBlue'],
        image: '🪟',
        description: 'Standard window piece'
    },
    {
        id: 'door_1x4x6',
        name: 'Door 1x4x6',
        width: 1,
        depth: 4,
        height: 6,
        studs: 4,
        category: 'architectural',
        subcategory: 'door',
        type: 'swing',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        movable: true,
        weight: 6.4,
        volume: 12.8,
        yearIntroduced: 1978,
        isCurrent: true,
        colors: ['brown', 'white', 'black', 'red'],
        image: '🚪',
        description: 'Swinging door'
    },

    // ============ MINIFIGURE PARTS ============
    {
        id: 'minifig_head',
        name: 'Minifigure Head',
        width: 1,
        depth: 1,
        height: 1,
        studs: 1,
        category: 'minifigure',
        subcategory: 'head',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: true,
        isTechnic: false,
        weight: 0.4,
        volume: 0.8,
        yearIntroduced: 1978,
        isCurrent: true,
        colors: ['yellow', 'flesh', 'brown', 'grey'],
        image: '👤',
        description: 'Minifigure head'
    },
    {
        id: 'minifig_torso',
        name: 'Minifigure Torso',
        width: 2,
        depth: 1,
        height: 2,
        studs: 2,
        category: 'minifigure',
        subcategory: 'torso',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 1.6,
        volume: 3.2,
        yearIntroduced: 1978,
        isCurrent: true,
        colors: ['all'],
        image: '👕',
        description: 'Minifigure torso'
    },
    {
        id: 'minifig_legs',
        name: 'Minifigure Legs',
        width: 2,
        depth: 1,
        height: 2,
        studs: 2,
        category: 'minifigure',
        subcategory: 'legs',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 1.6,
        volume: 3.2,
        yearIntroduced: 1978,
        isCurrent: true,
        colors: ['blue', 'black', 'red', 'brown'],
        image: '👖',
        description: 'Minifigure legs'
    },

    // ============ VEHICLE PARTS ============
    {
        id: 'wheel_rim',
        name: 'Wheel Rim',
        width: 3,
        depth: 3,
        height: 1,
        studs: 1,
        category: 'vehicle',
        subcategory: 'wheel',
        type: 'rim',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: true,
        isTechnic: false,
        diameter: 3,
        weight: 2.4,
        volume: 4.8,
        yearIntroduced: 1977,
        isCurrent: true,
        colors: ['black', 'grey', 'silver'],
        image: '⚫',
        description: 'Wheel rim for vehicles'
    },
    {
name: 'Wheel Tire',
        width: 3,
        depth: 3,
        height: 1,
        studs: 0,
        category: 'vehicle',
        subcategory: 'wheel',
        type: 'rubber',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: true,
        isTechnic: false,
        diameter: 3,
        weight: 1.2,
        volume: 2.4,
        yearIntroduced: 1977,
        isCurrent: true,
        colors: ['black'],
        image: '🔘',
        description: 'Rubber tire fits standard rim'
    },
    {
        id: 'steering_wheel',
        name: 'Steering Wheel',
        width: 1,
        depth: 2,
        height: 2,
        studs: 1,
        category: 'vehicle',
        subcategory: 'control',
        type: 'standard',
        isPlate: false,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        movable: true,
        weight: 0.4,
        volume: 0.8,
        yearIntroduced: 1970,
        isCurrent: true,
        colors: ['black', 'grey', 'white'],
        image: '🚗',
        description: 'Steering wheel on 1x2 console'
    },
    {
        id: 'windshield_2x4x2',
        name: 'Windshield 2x4x2',
        width: 2,
        depth: 4,
        height: 2,
        studs: 2,
        category: 'vehicle',
        subcategory: 'glass',
        type: 'slope',
        isPlate: false,
        isTile: false,
        isSlope: true,
        isRound: false,
        isTechnic: false,
        isTransparent: true,
        weight: 2.4,
        volume: 4.8,
        yearIntroduced: 1985,
        isCurrent: true,
        colors: ['transClear', 'transLightBlue'],
        image: '🚌',
        description: 'Standard vehicle windshield'
    },

    // ============ BASEPLATES ============
    {
        id: 'baseplate_16x16',
        name: 'Baseplate 16x16',
        width: 16,
        depth: 16,
        height: 0.333,
        studs: 256,
        category: 'basic',
        subcategory: 'baseplate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 12.8,
        volume: 25.6,
        yearIntroduced: 1978,
        isCurrent: true,
        colors: ['green', 'blue', 'tan', 'white'],
        image: '🟩',
        description: 'Small baseplate for building'
    },
    {
        id: 'baseplate_32x32',
        name: 'Baseplate 32x32',
        width: 32,
        depth: 32,
        height: 0.333,
        studs: 1024,
        category: 'basic',
        subcategory: 'baseplate',
        type: 'standard',
        isPlate: true,
        isTile: false,
        isSlope: false,
        isRound: false,
        isTechnic: false,
        weight: 51.2,
        volume: 102.4,
        yearIntroduced: 1978,
        isCurrent: true,
        colors: ['green', 'blue', 'tan', 'grey', 'white'],
        image: '🟩🟩\n🟩🟩',
        description: 'Standard large baseplate'
    }
];

export default LEGO_BRICK_TYPES;